# Generated by Django 5.1.1 on 2024-12-11 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceIni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_subrouter', models.CharField(max_length=12, verbose_name='子路由号')),
                ('node_mac', models.CharField(max_length=12, unique=True, verbose_name='设备地址')),
                ('sort', models.CharField(blank=True, max_length=4, null=True, verbose_name='设备短地址')),
                ('status', models.CharField(blank=True, max_length=2, null=True, verbose_name='设备状态')),
                ('spot_num', models.IntegerField(blank=True, null=True, verbose_name='对应车位数量')),
                ('spot_l', models.CharField(blank=True, max_length=30, null=True, verbose_name='左车位号')),
                ('spot_m', models.CharField(blank=True, max_length=30, null=True, verbose_name='中车位号')),
                ('spot_r', models.CharField(blank=True, max_length=30, null=True, verbose_name='右车位号')),
                ('cut_lx', models.IntegerField(blank=True, null=True, verbose_name='左车位x坐标')),
                ('cut_ly', models.IntegerField(blank=True, null=True, verbose_name='左车位y坐标')),
                ('cut_mx', models.IntegerField(blank=True, null=True, verbose_name='中车位x坐标')),
                ('cut_my', models.IntegerField(blank=True, null=True, verbose_name='中车位y坐标')),
                ('cut_rx', models.IntegerField(blank=True, null=True, verbose_name='右车位x坐标')),
                ('cut_ry', models.IntegerField(blank=True, null=True, verbose_name='右车位y坐标')),
                ('pic_sizex', models.IntegerField(blank=True, null=True, verbose_name='图片尺寸x')),
                ('pic_sizey', models.IntegerField(blank=True, null=True, verbose_name='图片尺寸y')),
                ('brightness', models.IntegerField(blank=True, null=True, verbose_name='亮度')),
                ('ver', models.CharField(blank=True, max_length=8, null=True, verbose_name='软件版本')),
            ],
            options={
                'verbose_name': '设备记录',
                'verbose_name_plural': '设备记录',
                'db_table': 'device_ini',
            },
        ),
        migrations.CreateModel(
            name='PanelIni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=12, unique=True, verbose_name='引导屏地址')),
                ('section', models.IntegerField(blank=True, null=True, verbose_name='显示区域')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='引导屏描述')),
                ('ver', models.CharField(blank=True, max_length=8, null=True, verbose_name='软件版本')),
            ],
            options={
                'verbose_name': '引导屏记录',
                'verbose_name_plural': '引导屏记录',
                'db_table': 'panel_ini',
            },
        ),
        migrations.CreateModel(
            name='SiteConfigeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Company', max_length=255, unique=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('development_date', models.CharField(blank=True, help_text='date', max_length=20, null=True)),
                ('name', models.CharField(blank=True, help_text='Configuration name', max_length=255, null=True)),
                ('server', models.CharField(blank=True, default='120.24.111.243', help_text='Server address', max_length=255, null=True)),
                ('user', models.CharField(blank=True, help_text='User name', max_length=255, null=True)),
                ('password', models.CharField(blank=True, help_text='Password for authentication', max_length=255, null=True)),
                ('send', models.CharField(blank=True, default='vchippub1', help_text='send name', max_length=255, null=True)),
                ('read', models.CharField(blank=True, default='vchipsub1', help_text='read name', max_length=255, null=True)),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
                'db_table': 'site_configeration',
            },
        ),
        migrations.CreateModel(
            name='SpotIni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_id', models.CharField(max_length=30, unique=True, verbose_name='车位号')),
                ('locate', models.CharField(blank=True, max_length=60, null=True, verbose_name='车位描述')),
            ],
            options={
                'verbose_name': '车位记录',
                'verbose_name_plural': '车位记录',
                'db_table': 'spot_ini',
            },
        ),
        migrations.CreateModel(
            name='SubrouterIni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=12, unique=True, verbose_name='子路由号')),
                ('node_num', models.IntegerField(blank=True, null=True, verbose_name='设备数量')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='子路由描述')),
                ('ver', models.CharField(blank=True, max_length=8, null=True, verbose_name='软件版本')),
            ],
            options={
                'verbose_name': '子路由记录',
                'verbose_name_plural': '子路由记录',
                'db_table': 'subrouter_ini',
            },
        ),
        migrations.CreateModel(
            name='MatchPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(blank=True, null=True, verbose_name='显示区域')),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.panelini', to_field='mac', verbose_name='引导屏地址')),
                ('spot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.spotini', to_field='spot_id', verbose_name='车位号')),
            ],
            options={
                'verbose_name': '车位引导屏匹配',
                'verbose_name_plural': '车位引导屏匹配',
                'db_table': 'match_panel',
            },
        ),
    ]
