# Generated by Django 5.1.4 on 2024-12-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceini',
            name='plate_l',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='左车位车牌号'),
        ),
        migrations.AddField(
            model_name='deviceini',
            name='plate_lx',
            field=models.IntegerField(blank=True, null=True, verbose_name='左车牌x坐标'),
        ),
        migrations.AddField(
            model_name='deviceini',
            name='plate_ly',
            field=models.IntegerField(blank=True, null=True, verbose_name='左车牌y坐标'),
        ),
        migrations.AddField(
            model_name='deviceini',
            name='plate_m',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='中车位车牌号'),
        ),
        migrations.AddField(
            model_name='deviceini',
            name='plate_mx',
            field=models.IntegerField(blank=True, null=True, verbose_name='中车牌x坐标'),
        ),
        migrations.AddField(
            model_name='deviceini',
            name='plate_my',
            field=models.IntegerField(blank=True, null=True, verbose_name='中车牌y坐标'),
        ),
        migrations.AddField(
            model_name='deviceini',
            name='plate_r',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='右车位车牌号'),
        ),
        migrations.AddField(
            model_name='deviceini',
            name='plate_rx',
            field=models.IntegerField(blank=True, null=True, verbose_name='右车牌x坐标'),
        ),
        migrations.AddField(
            model_name='deviceini',
            name='plate_ry',
            field=models.IntegerField(blank=True, null=True, verbose_name='右车牌y坐标'),
        ),
    ]
