# Generated by Django 5.1.1 on 2025-01-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_deviceini_plate_l_deviceini_plate_lx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpanel',
            name='spot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.spotini', to_field='spot_id', verbose_name='车位号'),
        ),
    ]
